##### PYTHON #####
#Kevin Wong
#kmw396 - 14240214
#December 04, 2018
#Assingment 4: Bank Transactions

.PHONY : build view clean

build :
	@# 
	chmod +x accounts

view :
	@\less accounts

clean :
	@\rm *.pyc
